export const ALL_TASK_REQUEST = 'ALL_TASK_REQUEST'
export const ALL_TASK_SUCCESS = 'ALL_TASK_SUCCESS'
export const ALL_TASK_FAIL = 'ALL_TASK_FAIL'

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST'
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS'
export const TASK_DETAILS_FAIL = 'TASK_DETAILS_FAIL'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

 
